version: '3.2'

services:
  storage:
    container_name: storage
    image: scireum/s3-ninja
    ports:
      - '9444:9000'
    volumes:
      - storage-data:/home/sirius/data

  database:
    container_name: database
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database/initdb:/docker-entrypoint-initdb.d/

  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

  service:
    container_name: service
    build:
      context: ./backend/service
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/service/src:/usr/local/app/src
    depends_on:
      storage:
        condition: service_started
      redis:
        condition: service_started
      database:
        condition: service_healthy
    restart: 'no'
    ports:
      - ${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./web:/usr/local/app
    depends_on:
      service:
        condition: service_started
    restart: 'no'
    ports:
      - ${FRONTEND_PORT:-80}:${FRONTEND_PORT:-80}

volumes:
  storage-data:
    external: false
  postgres-data:
    external: false
