version: '3.2'

services:
  database:
    image: daviddq/cat-colonies-database:latest
    container_name: database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_NAME
      - DB_PASS
      - DB_USER
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    networks:
      - network
    restart: unless-stopped

  service:
    image: daviddq/cat-colonies-service:latest
    container_name: service
    environment:
      - NODE_ENV
      - BACKEND_PORT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_SYNCHRONIZE
      - DB_USER
      - DB_PASS
    networks:
      - network
    ports:
      - 80:80
    restart: unless-stopped

  web:
    image: daviddq/cat-colonies-web:latest
    container_name: web
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgres-data:

networks:
  network:
