FROM node:16-alpine

WORKDIR /usr/local/app

COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY ormconfig.ts ./
COPY ./src ./src

#RUN npm install --production
RUN npm install
RUN npm run build

CMD [ "npm", "run", "start:prod" ]
#USER node
