version: '3.2'

services:
  database:
    image: daviddq/cat-colonies-database:latest
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2.5-alpine

  service:
    image: daviddq/cat-colonies-service:latest
    container_name: service
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - 80:80

volumes:
  postgres-data:
    external: false # TODO: revisar cómo debe estar esto en prod
