version: '3.2'

services:
  database:
    image: daviddq/cat-colonies-database:latest
    container_name: database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_NAME
      - DB_PASS
      - DB_USER
    restart: unless-stopped

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2.5-alpine

  service:
    image: daviddq/cat-colonies-service:latest
    container_name: service
    environment:
      - NODE_ENV
      - PORT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_SYNCHRONIZE
      - DB_USER
      - DB_PASS
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}

volumes:
  postgres-data:
    external: false # TODO: revisar cómo debe estar esto en prod
