FROM node:16-alpine

WORKDIR /usr/local/app

COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY ormconfig.ts ./
COPY ./src ./src

#RUN npm install --production
RUN npm install && npm run build && rm -R ./src

CMD [ "npm", "run", "start:prod" ]
#USER node
