version: '3.2'

services:
  database:
    container_name: database
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d/

  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

  service:
    container_name: service
    build:
      context: ./service
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./service/src:/usr/local/app/src
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    restart: 'no'
    ports:
      - 8080:8080

volumes:
  postgres-data:
    external: false
