version: "3.2"

services:
  database:
    container_name: database
    image: postgres:9.6.20-alpine
    env_file:
      - .env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/ # TODO: puede que esto esté mal

  redis:
    container_name: redis
    image: redis:6.2.5-alpine

  service:
    container_name: service
    image: daviddq/cat-colonies:latest
    restart: "always"
    environment:
      - NODE_ENV=production
      - PORT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_SYNCHRONIZE
      - DB_USER
      - DB_PASS
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  postgres-data:
    external: false # TODO: revisar cómo debe estar esto en prod
