version: '3.2'

services:
  database:
    container_name: database
    image: postgres:9.6.20-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    volumes:
      - ./src:/usr/local/app/src
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    ports:
      - 8080:3000

volumes:
  postgres-data:
    external: false
