name: Build web image

on:
  push:
    branches: ['main']
    paths: ['.github/workflows/**.web.yml', 'web/**']

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
          prefix: web

      - name: Set build number in version
        run: |
          npm run version:setBuild

      - name: Build web image
        run: |
          npm run docker:build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push web image
        run: |
          npm run docker:push
