name: Build service image

on:
  push:
    branches: ['main', 'develop']
    paths: ['.github/**', 'backend/service/**']

  # pull_request:
  #   branches: ["main", "develop"]
  #   paths: [".github/**", "backend/service/**"]

defaults:
  run:
    working-directory: ./backend/service

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build service image
        run: |
          npm run docker:build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push backend image
        run: |
          npm run docker:push
